// Reference only. Estate-specific acceptance limits must be independently confirmed before activation.
export const ieatReference = {
  title: 'ประกาศ กนอ. 76/2560 — รับเข้าระบบบำบัดน้ำเสียส่วนกลาง',
  url: 'https://www.ieat.go.th/web-upload/1xff0d34e409a13ef56eea54c52a291126/m_document/8213/14655/file_download/11440161adc9f368d838422d49b7de74.pdf',
  checkedAt: '2026-10-04',
  context: 'IEAT_CENTRAL',
};
export const ieatParameters = [
  {
    code: 'PH',
    name: 'ความเป็นกรด–ด่าง',
    unit: 'pH',
    dimension: 'ph',
    lower: 5.5,
    upper: 9,
    label: '5.5–9.0',
  },
  {
    code: 'BOD',
    name: 'BOD₅',
    unit: 'mg_L',
    dimension: 'concentration',
    lower: null,
    upper: 500,
    label: '≤ 500',
  },
  {
    code: 'COD',
    name: 'COD',
    unit: 'mg_L',
    dimension: 'concentration',
    lower: null,
    upper: 750,
    label: '≤ 750',
  },
  {
    code: 'TSS',
    name: 'ของแข็งแขวนลอย (TSS)',
    unit: 'mg_L',
    dimension: 'concentration',
    lower: null,
    upper: 200,
    label: '≤ 200',
  },
  {
    code: 'TDS',
    name: 'ของแข็งละลาย (TDS)',
    unit: 'mg_L',
    dimension: 'concentration',
    lower: null,
    upper: 3000,
    label: '≤ 3,000',
  },
  {
    code: 'OIL_GREASE',
    name: 'น้ำมันและไขมัน',
    unit: 'mg_L',
    dimension: 'concentration',
    lower: null,
    upper: 10,
    label: '≤ 10',
  },
  {
    code: 'TKN',
    name: 'ไนโตรเจน (TKN)',
    unit: 'mg_L',
    dimension: 'concentration',
    lower: null,
    upper: 100,
    label: '≤ 100',
  },
  {
    code: 'TEMPERATURE',
    name: 'อุณหภูมิ',
    unit: 'degC',
    dimension: 'temperature',
    lower: null,
    upper: 45,
    label: '≤ 45',
  },
];
