ALTER TABLE alerts ALTER COLUMN record_id DROP NOT NULL;
ALTER TABLE alerts ALTER COLUMN rule_id DROP NOT NULL;
ALTER TABLE alerts ADD COLUMN alert_type text NOT NULL DEFAULT 'THRESHOLD' CHECK(alert_type IN('THRESHOLD','MISSING_DATA','OVERDUE_ISSUE'));
